apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
   some-label: pod
spec:
  containers:
    - name: maven
      image: maven:3.8.3-openjdk-17
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2
    - name: docker
      image: docker:19.03
      command:
        - cat
      tty: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: m2
      hostPath:
        path: /root/.m2